services:
  app: # PHP
    build: .
    working_dir: /srv
    volumes:
      - ./app:/srv
    networks:
      - app_network
  basededatos:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: erick
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./datos:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app_network
  servidorweb: # Apache o Nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/srv
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
volumes:
  postgres_data:
networks:
  app_network: